{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n",
      "Setting up ONE API connection...\n",
      "2025-09-01 12:45:21,131 [INFO] No newer cache available\n",
      "Loading bwm_query results from fixtures/2023_12_bwm_release.csv\n",
      "\n",
      "==================================================\n",
      "STARTING DATA DOWNLOAD\n",
      "==================================================\n",
      "Testing with first 3 insertions...\n",
      "About to process 3 probe insertions:\n",
      "  1. EID: 6713a4a7-faed-4df2-acab-ee4e63326f8d, Probe: probe00, PID: 56f2a378-78d2-4132-b3c8-8c1ba82be598\n",
      "  2. EID: 56956777-dca5-468c-87cb-78150432cc57, Probe: probe01, PID: 47be9ae4-290f-46ab-b047-952bc3a1a509\n",
      "  3. EID: 56956777-dca5-468c-87cb-78150432cc57, Probe: probe00, PID: 6be21156-33b0-4f70-9a0f-65b3e3cd6d4a\n",
      "Processing 3 insertions\n",
      "eid 6713a4a7-faed-4df2-acab-ee4e63326f8d\n",
      "1 of 3 fail 56f2a378-78d2-4132-b3c8-8c1ba82be598 - Error: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "Detailed error for 56f2a378-78d2-4132-b3c8-8c1ba82be598: ALFObjectNotFound: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "0.09769841603701934 sec\n",
      "eid 56956777-dca5-468c-87cb-78150432cc57\n",
      "2 of 3 fail 47be9ae4-290f-46ab-b047-952bc3a1a509 - Error: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "Detailed error for 47be9ae4-290f-46ab-b047-952bc3a1a509: ALFObjectNotFound: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "0.09955937502672896 sec\n",
      "eid 56956777-dca5-468c-87cb-78150432cc57\n",
      "3 of 3 fail 6be21156-33b0-4f70-9a0f-65b3e3cd6d4a - Error: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "Detailed error for 6be21156-33b0-4f70-9a0f-65b3e3cd6d4a: ALFObjectNotFound: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "0.09981766599230468 sec\n",
      "0.0049544034661569945 min for the complete bwm set\n",
      "3, load failures:\n",
      "['56f2a378-78d2-4132-b3c8-8c1ba82be598', '47be9ae4-290f-46ab-b047-952bc3a1a509', '6be21156-33b0-4f70-9a0f-65b3e3cd6d4a']\n",
      "\n",
      "==================================================\n",
      "TEST SUCCESSFUL! Ready for full download.\n",
      "==================================================\n",
      "To download all data, uncomment the line below and run:\n",
      "# get_all_PETHs()  # This will download ALL ~700 probe insertions\n",
      "WARNING: Full download will take hours and require significant disk space!\n",
      "\n",
      "To proceed with concatenation after download, run:\n",
      "stack_concat(ephys=False)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/bwm_download/bwm_dmn/dmn_bwm.py\", line 1356, in get_all_PETHs\n",
      "    D = concat_PETHs(pid, vers=vers)\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/bwm_download/bwm_dmn/dmn_bwm.py\", line 399, in concat_PETHs\n",
      "    trials, mask = load_trials_and_mask(one, str(eid),\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/paper-brain-wide-map/brainwidemap/bwm_loading.py\", line 288, in load_trials_and_mask\n",
      "    sess_loader.load_trials()\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py\", line 1474, in load_trials\n",
      "    self.trials = self.one.load_object(\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/util.py\", line 166, in wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/util.py\", line 152, in wrapper\n",
      "    return method(self, eid, *args, **kwargs)\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/api.py\", line 1019, in load_object\n",
      "    raise alferr.ALFObjectNotFound(obj)\n",
      "one.alf.exceptions.ALFObjectNotFound: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/bwm_download/bwm_dmn/dmn_bwm.py\", line 1356, in get_all_PETHs\n",
      "    D = concat_PETHs(pid, vers=vers)\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/bwm_download/bwm_dmn/dmn_bwm.py\", line 399, in concat_PETHs\n",
      "    trials, mask = load_trials_and_mask(one, str(eid),\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/paper-brain-wide-map/brainwidemap/bwm_loading.py\", line 288, in load_trials_and_mask\n",
      "    sess_loader.load_trials()\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py\", line 1474, in load_trials\n",
      "    self.trials = self.one.load_object(\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/util.py\", line 166, in wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/util.py\", line 152, in wrapper\n",
      "    return method(self, eid, *args, **kwargs)\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/api.py\", line 1019, in load_object\n",
      "    raise alferr.ALFObjectNotFound(obj)\n",
      "one.alf.exceptions.ALFObjectNotFound: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/bwm_download/bwm_dmn/dmn_bwm.py\", line 1356, in get_all_PETHs\n",
      "    D = concat_PETHs(pid, vers=vers)\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/bwm_download/bwm_dmn/dmn_bwm.py\", line 399, in concat_PETHs\n",
      "    trials, mask = load_trials_and_mask(one, str(eid),\n",
      "  File \"/Users/mitchellostrow/Desktop/Projects/playingaround/ibl_data/paper-brain-wide-map/brainwidemap/bwm_loading.py\", line 288, in load_trials_and_mask\n",
      "    sess_loader.load_trials()\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py\", line 1474, in load_trials\n",
      "    self.trials = self.one.load_object(\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/util.py\", line 166, in wrapper\n",
      "    return method(self, *args, **kwargs)\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/util.py\", line 152, in wrapper\n",
      "    return method(self, eid, *args, **kwargs)\n",
      "  File \"/Users/mitchellostrow/opt/anaconda3/envs/iblenv/lib/python3.10/site-packages/one/api.py\", line 1019, in load_object\n",
      "    raise alferr.ALFObjectNotFound(obj)\n",
      "one.alf.exceptions.ALFObjectNotFound: trials \n",
      " The ALF object was not found.  This may occur if the object or namespace or incorrectly formatted e.g. the object \"_ibl_trials.intervals.npy\" would be found with the filters `object=\"trials\", namespace=\"ibl\"` \n"
     ]
    }
   ],
   "source": [
    "# IBL Brain-wide Map Dataset Download - FIXED VERSION\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import sys\n",
    "import os\n",
    "from one.api import ONE\n",
    "\n",
    "from pathlib import Path\n",
    "\n",
    "# Test connection first\n",
    "print(\"Setting up ONE API connection...\")\n",
    "try:\n",
    "    from one.api import ONE\n",
    "    \n",
    "    # Setup ONE API\n",
    "    ONE.setup(base_url='https://openalyx.internationalbrainlab.org', silent=True)\n",
    "    one = ONE(password='international', silent=True)\n",
    "    # Test a simple query to verify connection\n",
    "    from brainwidemap import bwm_query\n",
    "    df_test = bwm_query(one)\n",
    "    \n",
    "except Exception as e:\n",
    "    print(f\"Error setting up ONE API: {e}\")\n",
    "    print(\"Please check your internet connection and try again\")\n",
    "    raise\n",
    "\n",
    "# Import the main functions\n",
    "try:\n",
    "    from dmn_bwm import get_all_PETHs, stack_concat\n",
    "except Exception as e:\n",
    "    print(f\"Error importing dmn_bwm: {e}\")\n",
    "    raise\n",
    "\n",
    "print(\"\\n\" + \"=\"*50)\n",
    "print(\"STARTING DATA DOWNLOAD\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "# Start with a smaller subset for testing (first 3 insertions)\n",
    "print(\"Testing with first 3 insertions...\")\n",
    "try:\n",
    "    # Get first 3 insertions for testing (reduced from 10 for faster testing)\n",
    "    df_subset = df_test.head(3)\n",
    "    eids_subset = df_subset[['eid', 'probe_name', 'pid']].values\n",
    "    \n",
    "    print(f\"About to process {len(eids_subset)} probe insertions:\")\n",
    "    for i, (eid, probe, pid) in enumerate(eids_subset):\n",
    "        print(f\"  {i+1}. EID: {eid}, Probe: {probe}, PID: {pid}\")\n",
    "    \n",
    "    get_all_PETHs(eids_plus=eids_subset, vers='concat')\n",
    "    \n",
    "    print(\"\\n\" + \"=\"*50)\n",
    "    print(\"TEST SUCCESSFUL! Ready for full download.\")\n",
    "    print(\"=\"*50)\n",
    "    print(\"To download all data, uncomment the line below and run:\")\n",
    "    print(\"# get_all_PETHs()  # This will download ALL ~700 probe insertions\")\n",
    "    print(\"WARNING: Full download will take hours and require significant disk space!\")\n",
    "    \n",
    "except Exception as e:\n",
    "    print(f\"Error during download: {e}\")\n",
    "    import traceback\n",
    "    traceback.print_exc()\n",
    "\n",
    "print(\"\\nTo proceed with concatenation after download, run:\")\n",
    "print(\"stack_concat(ephys=False)\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "combining 3 insertions for version concat\n",
      "Loading bwm_query results from fixtures/2023_12_bwm_release.csv\n",
      "3 insertions combined\n",
      "339 good cells stacked before ephys\n",
      "embedding rastermap on concat...\n",
      "2025-09-01 12:43:50,258 [INFO] normalizing data across axis=1\n",
      "2025-09-01 12:43:50,263 [INFO] projecting out mean along axis=0\n",
      "2025-09-01 12:43:50,273 [INFO] data normalized, 0.01sec\n",
      "2025-09-01 12:43:50,274 [INFO] sorting activity: 339 valid samples by 2496 timepoints\n",
      "2025-09-01 12:43:50,669 [INFO] n_PCs = 200 computed, 0.41sec\n",
      "2025-09-01 12:43:50,819 [INFO] 88 clusters computed, time 0.56sec\n",
      "2025-09-01 12:43:56,567 [INFO] clusters sorted, time 6.31sec\n",
      "2025-09-01 12:43:56,618 [INFO] clusters upsampled, time 6.36sec\n",
      "2025-09-01 12:43:56,632 [INFO] rastermap complete, time 6.37sec\n",
      "embedding umap on concat...\n",
      "embedding pca on concat...\n",
      "339 cells in eventually\n"
     ]
    }
   ],
   "source": [
    "stack_concat(ephys=False,get_concat=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dict_keys(['ids', 'xyz', 'uuids', 'pid', 'axial_um', 'lateral_um', 'channels', 'len', 'fr', 'concat_z', 'isort', 'umap_z', 'pca_z'])\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "((339, 2), (339, 2))"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import numpy as np\n",
    "#load and make sure the data works\n",
    "pth_dmn = Path(one.cache_dir, 'dmn', 'res')\n",
    "datapath = Path(pth_dmn, f'concat_ephysFalse.npy')\n",
    "data = np.load(datapath, allow_pickle=True).flat[0]\n",
    "print(data.keys())\n",
    "data['pca_z'].shape,data['umap_z'].shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "iblenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
